 
################################################################################
# PostgreSQL 연결 설정
################################################################################
  
jdbc.datasource=jdbc/DataSource
jdbc.driverClass=org.postgresql.Driver
jdbc.url=jdbc:postgresql://localhost:5432/postgres
jdbc.username=postgres
jdbc.password=dldudwn1!
